[[redirects]]
  from = "/base/*"
  to = "http://ec2-54-180-106-175.ap-northeast-2.compute.amazonaws.com:8080/:splat"
  status = 200
  force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200