export const buttonType = {
  /*default type */
  _120x40_Primary: {
    width: "7.5rem",
    height: "2.5rem",
    padding: "0.5rem 3rem",
    backGround: "var(--light-primary)",
    hoverBackGround: "var(--primary)",
    color: "var(--white)",
    borderRadius: "4px",
  },
  _100x123_Primary: {
    width: "6.25rem",
    height: "7.6875rem",
    padding: "0.5rem 3rem",
    backGround: "var(--light-primary)",
    hoverBackGround: "var(--primary)",
    color: "var(--white)",
    borderRadius: "4px",
  },
  _120x40_Gray2: {
    width: "7.5rem",
    height: "2.5rem",
    padding: "0.5rem 3rem",
    backGround: "var(--gray2-subbtn)",
    hoverBackGround: "var(--gray3-border)",
    color: "var(--gray5-lowText)",
    borderRadius: "4px",
  },
  _100x35_Gray2: {
    width: "6.25rem",
    height: "2.1875rem",
    padding: "0rem 0rem",
    backGround: "var(--gray2-subbtn)",
    hoverBackGround: "var(--gray3-border)",
    color: "var(--gray5-lowText)",
    borderRadius: "4px",
  },
  _100x35_Primary: {
    width: "6.25rem",
    height: "2.1875rem",
    padding: "0rem 0rem",
    backGround: "var(--light-primary)",
    hoverBackGround: "var(--primary)",
    color: "var(--white)",
    borderRadius: "4px",
  },
  _150x45_White: {
    width: "9.5rem",
    height: "3rem",
    padding: "0.8125rem 1.1875rem",
    backGround: "var(--white)",
    hoverBackGround: "var(--white)",
    color: "var(--gray5-lowText)",
    borderRadius: "8px",
  },
} as const;
