export const buttonType = {
  /*default type */
  _120x40_Primary: {
    width: "120px",
    height: "40px",
    padding: "0.5rem 3rem",
    backGround: "var(--light-primary)",
    hoverBackGround: "var(--primary)",
    color: "var(--white)",
    borderRadius: "4px",
  },
  _100x123_Primary: {
    width: "100px",
    height: "123px",
    padding: "0.5rem 3rem",
    backGround: "var(--light-primary)",
    hoverBackGround: "var(--primary)",
    color: "var(--white)",
    borderRadius: "4px",
  },
  _120x40_Gray2: {
    width: "120px",
    height: "40px",
    padding: "0.5rem 3rem",
    backGround: "var(--gray2-subbtn)",
    hoverBackGround: "var(--gray3-border)",
    color: "var(--gray5-lowText)",
    borderRadius: "4px",
  },
  _100x35_Gray2: {
    width: "100px",
    height: "35px",
    padding: "0rem 0rem",
    backGround: "var(--gray2-subbtn)",
    hoverBackGround: "var(--gray3-border)",
    color: "var(--gray5-lowText)",
    borderRadius: "4px",
  },
  _100x35_Primary: {
    width: "100px",
    height: "35px",
    padding: "0rem 0rem",
    backGround: "var(--light-primary)",
    hoverBackGround: "var(--primary)",
    color: "var(--white)",
    borderRadius: "4px",
  },
} as const;
